### ISSUE TITLE
Best Practice for register_vector in ConnectionPool

### ISSUE THREAD

**Issue by JanKulbinski** [pgvector/pgvector-python#100]
I’m setting up a PGVectorClient class with a `ConnectionPool` and need clarification on the best way to handle `register_vector` function. Is it necessary to call `register_vector` on every query (when fetching connection from Pool) or can it be registered once when creating ConnectionPool - I guess not since every connection can be closed and new can be opened, right?

```python
class PGVectorClient:
    def __init__(self, conninfo):
        self.pool = ConnectionPool(conninfo, min_size=5, max_size=10, open=True)
        # Should register_vector be called here on every connection in pool? 

    def query_batch(self, queries):
        with ThreadPoolExecutor() as executor:
            results = list(executor.map(self.query, queries))
        return results

    def query(self, query_text):
        with self.pool.connection() as connection:
            # Should register_vector be called here in each query call? Is that a lot overhead? 
            connection.execute(query_text)
```

**Comment by ankane** [comment]
Hi @JanKulbinski, you'll want to use the `configure` option, which will be called when the pool starts a new connection. Added an example and tests in the commit above.

**Comment by JanKulbinski** [comment]
Thank you!
