### ISSUE TITLE
Support for Pydantic in pgvector-python

### ISSUE THREAD

**Issue by FallenChromium** [pgvector/pgvector-python#107]
Hey! Thanks for the library, hoping to get into using Postgres as a vectorstore with the blooming ecosystem of tools for pgvector :)

Here's one issue that I've encountered:
```py
raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.IsInstanceSchema (<class 'pgvector.sqlalchemy.vector.VECTOR'>)
```
For further information visit https://errors.pydantic.dev/2.10/u/invalid-for-json-schema

This happened when I tried to use a SQLModel model with FastAPI and one of the fields was typehinted as Vector.

I'm not sure whether this would necessarily be an issue on your side but I've had to switch the typehint to `List[float]` which might degrade the IDE experience quite a bit. What should be done for pgvector-python to support Pydantic? I might be able to allocate some of my time to make this happen.

**Comment by ankane** [comment]
Hi @FallenChromium, see https://github.com/pgvector/pgvector-python/issues/57#issuecomment-1968064333 for my current thoughts on supporting typing.
