### ISSUE TITLE
Set thresholds

### ISSUE THREAD

**Issue by aiseei** [pgvector/pgvector-python#13]
hi there ! 
It would be awesome if you could support threshold's with a param for all distance strategy's,   along the line of the PGVECTOR extension. 
https://github.com/pgvector/pgvector/issues/16

Saw this in the readme. 
Get items within a certain distance
session.scalars(select(Item).filter(Item.embedding.l2_distance([3, 1, 2]) < 5))

So please advise.

**Comment by ankane** [comment]
Hi @aiseei, this already works with all distance functions.

**Comment by aiseei** [comment]
hi .could not find this in the code or docs for SQLalchemy. Please advise.
