### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Oheed911** [pgvector/pgvector-python#14]
Hi, I am new to vector databases and trying to use this in a project, documentation for this is not in depth, can you please provide more detail on how to use it with python, may be give a simple but complete example where variables are not missing, like I was reading where the conn is coming from or where the mapped_column is coming from. 

If you could provide an indepth example on how to create a collection and then insert vector data and some other data in the same table and how to fetch and do similarity search. It would be great. Thanks!

**Comment by ankane** [comment]
Hi @Oheed911, there are full examples in the [examples](https://github.com/pgvector/pgvector-python/tree/master/examples) directory, which are linked to from the readme.
