### ISSUE TITLE
No support for vector deletion based on index? 

### ISSUE THREAD

**Issue by KeshavSingh29** [pgvector/pgvector-python#15]
Hi
Thanks for this awesome project. 
I was just wondering if deleting a vector given index is still in works or will not be supported ? 

Reason: 
I want to be able to have CRUD functionality and not always delete the whole vector DB and reinitialize in case my data has come changes or is constantly updating.

**Comment by ankane** [comment]
Hi @KeshavSingh29, this is already supported (it's the same as deleting any other data).
