### ISSUE TITLE
Can't register_vector(connection)

### ISSUE THREAD

**Issue by Stevod** [pgvector/pgvector-python#16]
I have installed pgvector on Ubuntu 22.04 and checked that as follows:

$sudo apt install postgresql-15-pgvector
[sudo] password for <user>:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
postgresql-15-pgvector is already the newest version (0.4.2-1.pgdg22.04+1).
0 to upgrade, 0 to newly install, 0 to remove and 8 not to upgrade.
I further check by running: 
CREATE EXTENSION vector;
and I get:
SQL Error [42710]: ERROR: extension "vector" already exists

So it looks as though everything is installed correctly.

however when I use the code as per docs:
```
from pgvector.psycopg2 import register_vector
register_vector(connection)
```
it throws an exception and I get:
vector type not found in the database

Python version is 3.10.9 and the connection is setup as follows:
```
        connection = psycopg2.connect(
            host=hostname, user=username, password=password,
            dbname=database)
        cur = connection.cursor()
        connection.autocommit = True
```

Help appreciated.

**Comment by Stevod** [comment]
Adding the Create Extension makes  no difference unfortunately.
Also, when I run this query OUTSIDE python, from a SQL client I get the error message below.```
  
SELECT allowed_domain,
COUNT(*) AS NUM_PAGES,
AVG(page_embed_vector) AS COMPANY_EMBED_VECTOR
FROM domains.pages_retrieved
GROUP BY allowed_domain
```
which gives error:

SQL Error [42883]: ERROR: function avg(domains.vector) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 47

Error position: line: 3 pos: 46

This points to a problem in the extension itself, as I think AVG is a function that is provided by the extension itself.

**Comment by Stevod** [comment]
p.s. same code seems to work fine on Windows/PostgreSQL

**Comment by ankane** [comment]
My guess is it's a permission or schema issue. What's the output of:

```sql
SELECT extname, extversion, nspname FROM pg_extension LEFT JOIN pg_namespace ON pg_namespace.oid = pg_extension.extnamespace;
```

on each platform?

**Comment by Stevod** [comment]
on Ubuntu:
plpgsql	1.0	pg_catalog
vector	0.4.2	domains

**Comment by Stevod** [comment]
on Windows:
plpgsql 1.0 pg_catalog
vector 0.4.2 public

So I guess you may be right about the permissions as it's a different (non-public) schema. What permissions should I need?

**Comment by ankane** [comment]
It looks the extension was created in the `domains` schema, but it's not part of the search path.

```sql
SHOW search_path;
```

I'd recommend creating it in the `public` schema, which is included in the search path by default.
