### ISSUE TITLE
Rename max_inner_product

### ISSUE THREAD

**Issue by lucasgadams** [pgvector/pgvector-python#17]
Just wondering why the comparator is called `max_inner_product`. Shouldn't it be `negative_inner_product`? Seems like it could be confusing. Thanks for making the package!

**Comment by ankane** [comment]
Hi @lucasgadams, thanks for the suggestion. I thought `max_inner_product` was better since the function is used for [maximum inner product search](https://en.wikipedia.org/wiki/Maximum_inner-product_search). I'd like to keep the current name for now, but may revisit / add an alias in the future.

**Comment by lucasgadams** [comment]
I'm not sure that really makes sense? Maximum inner product search is when you are trying to _maximize_ the inner product between _similar_ items (its a similarity metric). Here the function is actually the opposite, its a sort of inner product _distance_ (negative inner product). And I don't think you need use MIPS or the word max to explain the utility for inner product, it's ubiquitous in ML as a measure of similarity (i've worked in ml for 10 years and have never heard the specific phrase MIPS). I'd argue the reason why most people are using inner product comparison in the first place is they are actually doing cosine similarity and have already normalized vectors (such as openai). I see that you are the author or the original pgvector so I assume you know all this already. Just my 2 cents.
