### ISSUE TITLE
serialize PGVector for aws lambda

### ISSUE THREAD

**Issue by harniva14** [pgvector/pgvector-python#25]
i have the following code 

def get_vectorstore(connection_string):
    # Initialize the embedding function
    embedding_func_instance = MyEmbeddings()
    
    # Initialize the vectorstore from the existing database
    vectorstore = PGVector(connection_string=connection_string, embedding_function=embedding_func_instance)
    return vectorstore

Unable to marshal response: Object of type PGVector is not JSON serializable

**Comment by ankane** [comment]
Hi @harniva14, this library doesn't implement a `PGVector` class, so think you're using another library.
