### ISSUE TITLE
Django migration to add VectorField unable to find vector.control

### ISSUE THREAD

**Issue by devonbrackbill** [pgvector/pgvector-python#3]
I'm not able to get the Django extension working in a project. I used the instructions on the [README page](https://github.com/pgvector/pgvector-python#django), but I'm seeing the following error:
```
django.db.utils.OperationalError: could not open extension control file "/Library/PostgreSQL/14/share/postgresql/extension/vector.control": No such file or directory
```

Ideas:
1. pgvector is not installing correctly for my postgres installation
2. I'm not apply the first step to "Create the extension" on the README. (I'm interpreting this as "add a migration to the Django app's `migrations` directory.) 
3. do I need to add anything to `settings.py`?

# Steps I ran:
ran `pipenv install pgvector` (pipenv b/c I'm using a environment with Piplock).

My migration file:
```
from django.db import migrations
import pgvector.django
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_document_document_faiss_index'),  # a previous migration
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='document',
            name='document_embeddings',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
    ]
```

and my `models.py` file:
```
class Document(models.Model):
    ...
    document_embeddings = VectorField(dimensions=1536, null=True)
    ...
```

ran `python manage.py migrate` and got above error.

**Comment by devonbrackbill** [comment]
I ran `brew install pgvector/brew/pgvector`, but I'm still getting the above error, and `SELECT * FROM pg_extension WHERE extname = 'pgvector';` is empty.

**Comment by Yankzy** [comment]
I have the same exact [problem](https://stackoverflow.com/questions/75664004/install-pgvector-extension-on-mac)

**Comment by ankane** [comment]
Hey, the `could not open extension control file` error means the extension isn't installed on the database server.

@devonbrackbill The Homebrew instructions only works for Homebrew Postgres, and from the path in the error message (`/Library/PostgreSQL/14`), it looks like you're using a different Postgres installation. Try using the main (`git clone`) instructions.

@Yankzy Can you create a new issue on the pgvector repo with the output from the installation instructions?

fwiw, when it's installed, it'll show up in:

```sql
SELECT * FROM pg_available_extensions WHERE name = 'vector';
```

**Comment by devonbrackbill** [comment]
Thank you, this worked.

**Comment by devonbrackbill** [comment]
for posterity, making a symlink resolved the problem: `cd /Library/Developer/CommandLineTools/SDKs && sudo ln -s MacOSX.sdk MacOSX11.1.sdk` b/c the `make` command was looking specifically for `MacOSX11.1`.

**Comment by ankane** [comment]
Thanks for sharing. `make` gets the compiler flags from the Postgres installation, fwiw.
