### ISSUE TITLE
[peewee] using Model.get_or_create() doesn't work with pgvector

### ISSUE THREAD

**Issue by ricardofunke** [pgvector/pgvector-python#31]
Hello!

I'm trying to use the peewee method .get_or_create() in place of .create() but I'm getting the following error:

```
{...}
  File "/myprj/venv/lib/python3.11/site-packages/pgvector/peewee/__init__.py", line 16, in db_value
    return to_db(value)
           ^^^^^^^^^^^^
  File "/myprj/venv/lib/python3.11/site-packages/pgvector/utils/__init__.py", line 37, in to_db
    return '[' + ','.join([str(float(v)) for v in value]) + ']'
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object is not iterable
```

Can you help to find out whether is this a bug or something I'm doing wrong?

Thanks!

**Comment by ankane** [comment]
Hi @ricardofunke, it should work if you use a NumPy array instead of a list:

```python
Item.get_or_create(embedding=np.array([4, 5, 6]))
```

I don't see a way to make it work with lists at the moment.

**Comment by ankane** [comment]
It looks like `AsIs(value)` and `Item.embedding.to_value(value)` work as well, but think that might be the best we can do for now.
