### ISSUE TITLE
`register_vector(conn)` yields `psycopg.ProgrammingError: vector type not found in the database`

### ISSUE THREAD

**Issue by costa** [pgvector/pgvector-python#33]
I'm using the latest version at the time of writing (0.2.2) and tried two latest versions of ankane/pgvector image (v0.5.0 and v0.4.4) as well as installed the extension myself.

**Comment by ankane** [comment]
Hi @costa, make sure the extension has been created before calling `register_vector`.

```python
conn.execute('CREATE EXTENSION IF NOT EXISTS vector')
```

**Comment by costa** [comment]
@ankane Thanks, that's what I ended up doing, so I don't need to call `register_vector`, it works with just the `CREATE EXTENSION ...`.
