### ISSUE TITLE
[Django] Using null=True raises error

### ISSUE THREAD

**Issue by keithhackbarth** [pgvector/pgvector-python#35]
If `null=True` is passed to a VectorField in Django, the field will be created successfully but both reads and writes to the field will fail.

```
pgvector/django/__init__.py", line 47, in validate
    super().validate(value.tolist(), model_instance)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tolist'
```

Will look into writing a PR if I have time.

**Comment by ankane** [comment]
Thanks @keithhackbarth, should be fixed in the commit above.

**Comment by keithhackbarth** [comment]
Amazing!!! Thank you @ankane. Super impressed 🤩
