### ISSUE TITLE
How to set ivfflat.probes for indexed embeddings

### ISSUE THREAD

**Issue by simonschoenhofen** [pgvector/pgvector-python#36]
Hey! 

I wanted to ask how I can set ivfflat.probes for indexed embeddings?  Like in 
https://github.com/pgvector/pgvector#query-options

Thank you

**Comment by ankane** [comment]
Hi @simonschoenhofen, you can execute that statement with your database library. With psycopg 3, it'll be:

```python
conn.execute('SET ivfflat.probes = 10')
```
