### ISSUE TITLE
Unable to run the extension migration

### ISSUE THREAD

**Issue by peter-stuart-turner** [pgvector/pgvector-python#39]
I'm on Postgres13, getting this:

django.db.utils.OperationalError: could not open extension control file "/usr/local/share/postgresql/extension/vector.control": No such file or directory

**Comment by ankane** [comment]
Hi @peter-stuart-turner, that error means pgvector isn't installed on your database server.

**Comment by peter-stuart-turner** [comment]
Ah thanks very much, have sorted it now
