### ISSUE TITLE
No operator matches the given name and argument types

### ISSUE THREAD

**Issue by Ritaja** [pgvector/pgvector-python#4]
When I try to retrieve/query embeddings from db: 

```python
from pgvector.psycopg import register_vector
import psycopg
conn = psycopg.connect(dbname='db')
conn.autocommit = True
register_vector(conn)
conn.execute('SELECT * FROM document ORDER BY embedding <=> %s LIMIT 1', (embeddings,))
rows = cur.fetchall()
```
I get:
```
UndefinedFunction: operator does not exist: vector <=> double precision[]
LINE 1: SELECT * FROM document ORDER BY embedding <=> $1 LIMIT 1
                                                  ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

What am I doing wrong ? 

lib version: 
psycopg 3.1.8
also observed with lib:
psycopg2-binary 2.9.5

**Comment by ankane** [comment]
Hey @Ritaja, you can either convert embedding to a NumPy array (`np.array(embedding)`) or add an explicit type cast to the query:

```python
conn.execute('SELECT * FROM document ORDER BY embedding <=> %s::vector LIMIT 1', (embeddings,))
```

**Comment by luckydrq** [comment]
@ankane @Ritaja  I have the same error but with a little difference in type: 

**operator does not exist: double precision[] <-> double precision[]**

In my case, vectors to be stored are in high precision, for example: ```[0.01147944740073234, 0.04085996856090725, 0.0280889704298014,......]```

So i followed the [document](https://github.com/pgvector/pgvector?tab=readme-ov-file#can-i-store-vectors-with-more-precision) to create a column(named "embedding") of `double precision[]` type to store vector. Here are my table info:

```
postgres=# \d icome_assistant_test
                                     Table "public.icome_assistant_test"
  Column   |          Type          | Collation | Nullable |                     Default
-----------+------------------------+-----------+----------+--------------------------------------------------
 id        | integer                |           | not null | nextval('icome_assistant_test_id_seq'::regclass)
 intent    | character varying(128) |           |          |
 content   | text                   |           |          |
 score     | double precision       |           |          |
 embedding | double precision[]     |           |          |
Indexes:
    "icome_assistant_test_pkey" PRIMARY KEY, btree (id)
    "icome_assistant_test_embedding_idx" hnsw ((embedding::vector(1536)) vector_cosine_ops)
Check constraints:
    "icome_assistant_test_embedding_check" CHECK (vector_dims(embedding::vector) = 1536)
```

According to the [doc](https://github.com/pgvector/pgvector?tab=readme-ov-file#can-i-store-vectors-with-more-precision), vector should be converted to a string wrapped in curly braces when being inserted：
```sql
-- use {} instead of [] for Postgres arrays
INSERT INTO items (embedding) VALUES ('{1,2,3}'), ('{4,5,6}');
```

And my insert implementation is as below:
```python
from psycopg.sql import SQL, Identifier

with pool.connection() as conn:
    conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
    register_vector(conn)

    with conn.cursor() as cur:
        cur.execute(
            SQL("update {} set embedding=%s where id=%s").format(
                Identifier(table_name)
            ),
            ("{" + str(doc.vector)[1:-1] + "}", int(doc.id)),
        )
        # ...
```

Also the doc mentions that query can be performed like this:
```sql
SELECT * FROM items ORDER BY embedding::vector(3) <-> '[3,1,2]' LIMIT 5;
```

So my query implementation is as below:
```python
from pgvector.psycopg import register_vector

with pool.connection() as conn:
    conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
    register_vector(conn)

    cur = conn.execute(
        SQL(
            "select * from {} order by embedding::vector(1536) <-> %s"
            + f" limit 5"
        ).format(Identifier(table_name)),
        (doc.vector,),
     )
     # ...
```

I don't know where goes wrong? Help appreciated.

Extra info:
- vector has 1536 dimensions.
- dependencies:
  - pgvector==0.2.4
  - psycopg==3.1.16
  - psycopg-binary==3.1.16
  - psycopg-pool==3.2.0

**Comment by jkatz** [comment]
`pgvector` currently supports 4-byte floats, not 8-byte floats. Is there a specific reason you need 8-byte floats?

**Comment by ankane** [comment]
@luckydrq I'm not sure how to reproduce, but if you can create a new issue with a minimal, self-contained repro script like the one below, happy to look into it more.

```python
import psycopg
from pgvector.psycopg import register_vector

conn = psycopg.connect(dbname="repro", autocommit=True)
conn.execute('CREATE EXTENSION IF NOT EXISTS vector')
register_vector(conn)

conn.execute('DROP TABLE IF EXISTS items')

conn.execute('CREATE TABLE items (id bigserial PRIMARY KEY, embedding double precision[])')

conn.execute('INSERT INTO items (embedding) VALUES (%s)', ('{1,2,3}',))

rows = conn.execute("SELECT * FROM items ORDER BY embedding::vector(3) <-> %s LIMIT 5", ('[3,1,2]',)).fetchall()
print(rows)
```

**Comment by luckydrq** [comment]
> `pgvector` currently supports 4-byte floats, not 8-byte floats. Is there a specific reason you need 8-byte floats?

Is 4-byte

For higher precision vector store, for example:
 ```[0.01147944740073234, 0.04085996856090725, 0.0280889704298014,......]```

Coming from [this issue](https://github.com/pgvector/pgvector/issues/182) and [document](https://github.com/pgvector/pgvector?tab=readme-ov-file#can-i-store-vectors-with-more-precision)

**Comment by luckydrq** [comment]
@ankane @jkatz  Thanks for your help. Got the problem done finally due to very stupid reason:

```python
cur = conn.execute(
    SQL(
        "select * from {} order by embedding::vector(1536) <-> %s"
        + f" limit 5"
    ).format(Identifier(table_name)),
    ### should convert to string: str(doc.vector)
    (doc.vector,),
)
```

```doc.vector``` -> ```str(doc.vector)```
