### ISSUE TITLE
How to rebuild indexes with Django?

### ISSUE THREAD

**Issue by lesser-panda** [pgvector/pgvector-python#41]
Newbie questions here,

I am planning to use pgvector with Django. I am wondering how should I rebuild a IVFFLAT or HNSW index as I add more embeddings to the database?

**Comment by ankane** [comment]
Hi @lesser-panda, indexes are updated incrementally, so you shouldn't need to reindex in many cases, but if needed, you can run:

```sql
REINDEX INDEX CONCURRENTLY index_name;
```

https://www.postgresql.org/docs/current/sql-reindex.html
