### ISSUE TITLE
ModuleNotFoundError: No module named 'pgvector.psycopg2'; 'pgvector' is not a package

### ISSUE THREAD

**Issue by himsgpt** [pgvector/pgvector-python#42]
I have installed and imported both **pgvector-0.2.3** and  **psycopg2-2.9.9** but on importing below register vector i get the error as follows:

`from pgvector.psycopg2 import register_vector`
`ModuleNotFoundError: No module named 'pgvector.psycopg2'; 'pgvector' is not a package`

It was working few months ago. Has there been any change?

**Comment by SeptSkyTime** [comment]
> I have installed and imported both **pgvector-0.2.3** and **psycopg2-2.9.9** but on importing below register vector i get the error as follows:
> 
> `from pgvector.psycopg2 import register_vector` `ModuleNotFoundError: No module named 'pgvector.psycopg2'; 'pgvector' is not a package`
> 
> It was working few months ago. Has there been any change?

I met the same error, how do you resolve that?
thanks!

**Comment by ankane** [comment]
Make sure your file isn't named `pgvector.py` (otherwise, it conflicts with the package).

**Comment by SeptSkyTime** [comment]
> Make sure your file isn't named `pgvector.py` (otherwise, it conflicts with the package).

Thank you so much, , that's exactly the issue.
