### ISSUE TITLE
Setting HNSW ef_search variable

### ISSUE THREAD

**Issue by creepykedi** [pgvector/pgvector-python#43]
No matter what I do, ef_search defaults to 40, so I'm always limited to 40 results. Can't seem to find a way to pass that variable in this wrapper, works fine in sql directly with 
SET hnsw.ef_search = N;
Any way to do it now? (I'm using django)

**Comment by ankane** [comment]
Hi @creepykedi, you can use:

```python
with connection.cursor() as cursor:
    cursor.execute('SET hnsw.ef_search = 100')
```

https://docs.djangoproject.com/en/4.2/topics/db/sql/#executing-custom-sql-directly
