### ISSUE TITLE
How to set query options (e.g. # of ivfflat.probe) when querying a table with IVFFlat or HNSW index?

### ISSUE THREAD

**Issue by lesser-panda** [pgvector/pgvector-python#46]
As mentioned in the instructions of pgvector (https://github.com/pgvector/pgvector#query-options), there are several query options that can be set at the time of querying, if the table contains an IVFFlat or HNSW index. How can we set these options when using this library?

**Comment by ankane** [comment]
Hi @lesser-panda, check out #36.
