### ISSUE TITLE
Question: How to access distance values when querying with Django? 

### ISSUE THREAD

**Issue by pranciskus** [pgvector/pgvector-python#5]
Hi there! Wanted to ask how one should access calculated diff values when ordering by L2Distance in Django?

```
from pgvector.django import L2Distance

Item.objects.order_by(L2Distance('embedding', [3, 1, 2]))[:5]
```
[3, 1, 2] vs. items[0].embedding?

Also, is it possible to get rows at a certain distance?

```
SELECT * FROM items WHERE embedding <-> '[3,1,2]' < 5;
```

**Comment by zachbellay** [comment]
Hey @pranciskus, I was wondering the same and as per @ankane 's suggestion, this seems to work:

```py
from pgvector.django import L2Distance

items = Item.objects.order_by(
    L2Distance('embedding', [3, 1, 2])
).annotate(
    dist=L2Distance('embedding', [3, 1, 2])   
)[:5]

for item in items:
    print(item, item.dist)
```

**Comment by ankane** [comment]
Added examples for getting the distance and getting rows within a certain distance.
