### ISSUE TITLE
Question on (testing) cosine_similiarity with WHERE clauses

### ISSUE THREAD

**Issue by pmalacho-mit** [pgvector/pgvector-python#55]
Hello! First off, thank you for this library and the terrific examples (I was especially appreciative of the clear-cut SQLModel starter code). 

This is somewhat of a question, and somewhat just asking for confirmation that my interpretation is correct (as I was really scratching my head before starting to, maybe, make sense of things). I'm working on a SQModel-based codebase where I have approximately the following schema:

- Document
   - id: UUID
- Chunk
   - id: UUID
   - document_id == Document.id (foreign key relationship)
- Embedding(s)
   - id: UUID
   - vector: Vector
   - chunk_id == Chunk.id (foreign key relationship)

   
(embeddings are stored separately from chunks since I want to experiment with different embedding models, and thus want to support multiple embedding tables)

I adapted this codebase's [SQLModel tests](https://github.com/pgvector/pgvector-python/blob/master/tests/test_sqlmodel.py) to see if my querying strategy (which incorporated a `WHERE` clause) was working correctly. Things were fine for `l2_distance` and `max_inner_product` but my results were nondetermistic for `cosine_distance` -- sometimes they passed, sometimes they didn't. 

I was able to make sense of this after learning that (at least in postgres) adding a `WHERE` clause can introduce some non-determinism in how fields with the same value are ordered. Since for `cosine_distance`, both `[1,1,1]` and `[2,2,2]` are 0 degrees away from the test case `[1,1,1]` (right?) I assume in my tests they were just flip-flopping in order. 

Does this checkout to other folks? I'm not a very experienced database nor embeddings developer..

**Comment by ankane** [comment]
Hi @pmalacho-mit, if two rows have the same distance (like in the example above), the database can return them in either order. You can add a second sort expression to make it deterministic.

```sql
SELECT ... ORDER BY vector <=> $1, id
```

https://www.postgresql.org/docs/current/queries-order.html

**Comment by pmalacho-mit** [comment]
Great, thanks @ankane ! That's very clear. 

I actually had tried that, which was not working for me, but now that you mention it I again I realize it's simply because I was relying on a `default_factory` function to generate those UUIDs fresh it each time.

I have a feeling that was actually causing the really wacky non-determinism I was seeing, and just didn't realize in my confusion. 

Thanks for the quick reply and the help!
