### ISSUE TITLE
[SQLModel] Select both columns and distance in the same query

### ISSUE THREAD

**Issue by mbignotti** [pgvector/pgvector-python#56]
Hi!
The README shows the following example for SQLModel:
```python
from pgvector.sqlalchemy import Vector
from sqlalchemy import Column

class Item(SQLModel, table=True):
    embedding: List[float] = Field(sa_column=Column(Vector(3)))

# (...)

item = Item(embedding=[1, 2, 3])
session.add(item)
session.commit()

# (...)

# Get the nearest neighbors to a vector
session.exec(select(Item).order_by(Item.embedding.l2_distance([3, 1, 2])).limit(5))


# (...)

# Get the distance
session.exec(select(Item.embedding.l2_distance([3, 1, 2])))
```

I was wondering, how do you select the neighbors and the distance (for each neighbor) in the same query?
I tried 
```python
session.exec(select(Item, Item.embedding.l2_distance([3, 1, 2]).label("distance")).order_by(Item.embedding.l2_distance([3, 1, 2])).limit(5))
```
and it works, but distance is not included as an `Item` attribute. The output looks like (numbers invented):
```python
[(Item(embedding=array([1, 2, 3], dtype=float32)), 2.335), (Item(embedding=array([3, 2, 1], dtype=float32)), 2.446)]
```
I would like to have, instead:
```python
[Item(embedding=array([1, 2, 3], dtype=float32), distance=2.335), Item(embedding=array([3, 2, 1], dtype=float32), distance=2.446)]
```
I guess I have to write the `Item` model differently, but I'm not sure how to write the distance attribute, since it depends on another column (`embedding`) and on external data (the actual query embedding). 
  
Thanks!

**Comment by ankane** [comment]
Hi @mbignotti, that's how you would get the object and distance. You can then use any Python code to transform the results as needed.

**Comment by mbignotti** [comment]
I solved by specifying one by one all the columns that I need. However, that reduces a lot the convenience of using sqlalchemy/sqlmodel, as the result is now a `Row`, not an instance of `Item` (or a list of `Item`).
Maybe there are other solutions, but I haven't found any.
