### ISSUE TITLE
sqlalchemy.exc.InvalidRequestError: Unknown PG numeric type: 24664

### ISSUE THREAD

**Issue by saeedesmaili** [pgvector/pgvector-python#6]
Thanks for this amazing library.

I'm using it with fastapi and sqlalchemy, and I'm able to insert vectors to the database. But when I need to query the table (for updating a row for example), I get the following error:

> File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 525, in result_processor
> raise exc.InvalidRequestError(
> sqlalchemy.exc.InvalidRequestError: Unknown PG numeric type: 24664

I had the issue with inserting vectors as well, but I fixed it by changing from:

```python
def create_record(session: Session, record: RecordCreate):
    new_record = Record(**record.dict())
    session.add(new_record)
    session.commit()
    session.refresh(new_record)
    return new_record
```

to:

```python
def create_record(session: Session, record: RecordCreate):
    new_record = Record(**record.dict())
    session.add(new_record)
    session.commit()
    # session.refresh(new_record)
    return True
```

I have another function to update a database record if it exists, and it fails with the error mentioned above:

```python
def create_or_update_record(session: Session, record: RecordCreate):
    db_record = session.exec(
        select(Record).where(Record.id == record.id)
    ).first()
    # rest of the function
```

Error:

> api_1        |   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/fastapi.py", line 84, in _sentry_call
> api_1        |     return old_call(*args, **kwargs)
> api_1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^
> api_1        |   File "/usr/src/app/app/api/controllers/records.py", line 119, in create_or_update_record_endpoint
> api_1        |     return create_or_update_record(session, record)
> api_1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> api_1        |   File "/usr/src/app/app/api/controllers/records.py", line 53, in create_or_update_record
> api_1        |     db_record = session.exec(
> api_1        |                     ^^^^^^^^^^^^^
> api_1        |   File "/usr/local/lib/python3.11/site-packages/sqlmodel/orm/session.py", line 60, in exec
> api_1        |     results = super().execute(
> api_1        |               ^^^^^^^^^^^^^^^^
> rest of the error ...
> api_1        |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/type_api.py", line 702, in _cached_result_processor
> api_1        |     d[coltype] = rp = d["impl"].result_processor(dialect, coltype)
> api_1        |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> api_1        |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 525, in result_processor
> api_1        |     raise exc.InvalidRequestError(
> api_1        | sqlalchemy.exc.InvalidRequestError: Unknown PG numeric type: 24664

Any idea how can I fix this?

**Comment by saeedesmaili** [comment]
Adding more info. Here is the definition of the model in fastapi:

```python
from pgvector.sqlalchemy import Vector

class Record(SQLModel, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    text: str = Field(default=None)
    start: int = Field(default=None)
    token_count: int = Field(default=None)
    embedding: List[float] = Field(default=None, sa_column=Vector(1536))
```

**Comment by ankane** [comment]
Hi @saeedesmaili, updating `sa_column` to `Column(Vector(1536))` should fix it.
