### ISSUE TITLE
Sqlalchemy example not working

### ISSUE THREAD

**Issue by mkornacker** [pgvector/pgvector-python#65]
I just tried to create an index via Sqlalchemy, following the instructions in the readme:
idx = sql.Index(
            '...', <instance of sa.Column>,
            postgresql_using='hnsw',
            postgresql_with={'m': 16, 'ef_construction': 64},
            postgresql_ops={'embedding': 'vector_cosine_ops'}
        )
idx.create(bind=...)

which ends up running (notice that the vector_cosine_ops didn't make it into the statement):
'CREATE INDEX idx_617bbefd304a4d1abbef9cfb75012fb9_0 ON tbl_617bbefd304a4d1abbef9cfb75012fb9 USING hnsw (idx_0_col) WITH (m = 16, ef_construction = 64)'

and I'm getting the following error:
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) data type vector has no default operator class for access method "hnsw"

This is on pgvector 0.2.5

**Comment by ankane** [comment]
Hi @mkornacker, I'm not sure how to reproduce. [The test](https://github.com/pgvector/pgvector-python/blob/ad32dc0f00e905c7a6a245ed20bcdbffcfe4e627/tests/test_sqlalchemy.py#L28-L35) works fine.

**Comment by fablerq** [comment]
@mkornacker I faced the same issue, I changed "{'embedding': 'vector_cosine_ops'}" to the actual name of my vector field and it worked
