### ISSUE TITLE
Questions on 

### ISSUE THREAD

**Issue by vade** [pgvector/pgvector-python#66]
Hi

We are also using `PGVector` to do to embedding search. 
We are using `Django-filter` for faceted search on model fields. 
We are using a `MrThearMan/graphene-django-query-optimizer` to provide `.only`, `prefetch_related` and `select_related` optimizations to ensure our generated SQL runs fast.

We've used `EXPLAIN_ANALYZE` and noticed that PGVector appears to be running on all rows on the table, and then filtering occurs, which is suboptimal.

We want to ensure that our PGVector embedding calculations run only on pre filtered results. 

Does anyone have any real advice on how to 

* properly formulate Django ORM queries to do this while allowing the flexibility of `Django-Filter` ? 
* where the best place to insert overrides on filter sets ordering to ensure performance is respected? 

Thanks!

**Comment by ankane** [comment]
Hi @vade, the Postgres planner should select the most efficient plan in most cases (if not, try running `ANALYZE` or using [extended statistics](https://www.postgresql.org/docs/current/planner-stats.html#PLANNER-STATS-EXTENDED)).
