### ISSUE TITLE
Django support for empty fields

### ISSUE THREAD

**Issue by Cdingram** [pgvector/pgvector-python#67]
In Django it would be very useful to be able to use null=True and/or blank=True as is common for model fields so that the vector can be calculated after the object is created for example. Currently doing this creates an error "vector must have at least 1 dimension".

**Comment by ankane** [comment]
Hi @Cdingram, it already support this.

**Comment by Cdingram** [comment]
You're right, my apologies. For whatever reason, it's not possible to save it as blank via the django admin dashboard. It seems like for whatever reason the form there tries to default blank to '[]'. That is the actual issue, although I'm not sure if that issue is possible to fix here or upstream.

**Comment by Cdingram** [comment]
Fixed in PR #68
