### ISSUE TITLE
NameError: name 'psycopg' is not defined when register_vector fails

### ISSUE THREAD

**Issue by chriswmann** [pgvector/pgvector-python#77]
Hi,

As of version 0.3.0, when I call `register_vector` for `psycopg`, if the registration fails (e.g. with `raise psycopg.ProgrammingError('vector type not found in the database')`), there's an additional error: `NameError: name 'psycopg' is not defined`.

Looking at `pgvector/psycopg/vector.py`, it looks like the psycopg module just needs to be imported.

I'm happy to create a PR for this, if needed.

**Comment by ankane** [comment]
Hi @chriswmann, thanks for reporting! Fixed in the commit above.
