### ISSUE TITLE
Have you tought about supporting Piccolo?

### ISSUE THREAD

**Issue by jackbravo** [pgvector/pgvector-python#81]
Another interesting Python ORM is https://github.com/piccolo-orm/piccolo/

Have you thought about adding support for it?

This is how they currently suggest using pgvector, through raw SQL:

https://github.com/piccolo-orm/piccolo/discussions/988 this points to the other URL ->
https://github.com/piccolo-orm/piccolo/discussions/876

**Comment by ankane** [comment]
Hi @jackbravo, thanks for sharing. I don't think it's common enough to add/support right now, but someone could create a separate package for it (looks like it supports [custom types](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/advanced.html#how-to-create-custom-column-types)).
