### ISSUE TITLE
Adding type annotations?

### ISSUE THREAD

**Issue by pamelafox** [pgvector/pgvector-python#82]
I ran mypy on a codebase that uses pgvector, and saw that pgvector doesn't seem to have type annotations currently. Have you considered adding those, to allow for better type checking?

**Comment by ankane** [comment]
Hi @pamelafox, I still have similar thoughts as https://github.com/pgvector/pgvector-python/issues/57#issuecomment-1968064333 (not something I'd like to commit to supporting right now). However, someone could create a separate stubs package (similar to [this one](https://github.com/typeddjango/django-stubs) for Django).

**Comment by pamelafox** [comment]
Ah, I forgot about that discussion. We'll add pgvector to the ignore list for mypy for now, thanks for the reply!

**Comment by ankane** [comment]
Just fyi: the latest release (0.5.0) has experimental support for type hints.
