### ISSUE TITLE
Corrupted NP Array after many inserts into DB

### ISSUE THREAD

**Issue by vade** [pgvector/pgvector-python#9]
Hi there

Firstly, thank you for PGVector. This library is really awesome.

I'm noticing some interesting behavior when benchmarking lots of vector inserts, I will occasionally get an error like:

```
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type vector: "0&37601622029971404"
LINE 1: ...e speaking a line', 'Line 23: This is meta', 220, '[0.693288...
```

or 

```
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type vector: "0.15788865441>03905"
LINE 1: ...e speaking a line', 'Line 13: This is meta', 263, '[0.966757...
```

We are inserting via SQLAlchemy like so:

```
inserted_object = ObjectClass(randNum1=random.randrange(0, 100), randNum2=random.randrange(0, 100),  embedding =  np.random.rand(1280).tolist()  )
``` 

In a fairly tight loop so we can test PGVector for our schema. 

We run Postgres /  PGVector from a Docker container, and have tested on a few platforms (M2 Mac, X86_64 Ubuntu Linux)

Our base docker image:

```
FROM python:3.8-slim

RUN apt-get update && apt-get install -y gcc git libpq-dev

ARG GID_
ARG UID_

RUN addgroup --gid $GID_ appuser
RUN adduser --disabled-password --gecos '' --uid $UID_ --gid $GID_ appuser

# Ensure installation directory used by pip is available on $PATH
ENV PATH="/home/appuser/.local/bin:${PATH}"

WORKDIR /app

ARG GITHUB_USER
ARG GITHUB_ACCESS_TOKEN

USER appuser

COPY --chown=appuser:appuser ./requirements/requirements.txt .

RUN pip3 install -r requirements.txt
```

Our Requirements.txt which is auto-run on docker building:

```
alembic
pgvector
#psycopg[binary,pool]
psycopg2-binary==2.9.6
SQLAlchemy==2.*
weaviate-client==3.15.5
```

We've noticed that on our Ubuntu Linux test system we get intermittent failures like the one above.

Is  this a known issue, or perhaps something more to do with how np.Array is being ingested into SQLAlchemy that can sometimes cause errors?

We haven't seen this on Apple Silicon, and only see the error intermittently when running on Ubuntu after a few hundred thousand inserts. 

Thank you in advance.

**Comment by ankane** [comment]
Hi @vade, I'm not sure what would cause this. Can you try getting the full statement from the Postgres server log?

**Comment by vade** [comment]
Hi @ankane - thanks for the prompt response. I'll poke around, forgive me, is there a specific method for fetching the logs that you prefer?

As an aside, I think I resolved the issue - however I don't thinks a 'fix', I'm just avoiding perhaps an edge case in some of the underlying code.

In our SQLAlchemy benchmarking code, we have some nested loops which create Python class objects associated with a SQLAlchemy class/schema definition - some of which have a PGVector associated.

We had a DB commit on one of the outer loops. By making the commit sooner in the inner loop, it seems that the issue has been resolved. My intuition is that we aren't creating lots of overhead in the SQLAlchemy code.

This leads me to believe some sort of memory compression or optimization, or underlying issue was occurring with LOTS of objects and LOTs of NP Arrays 

Whats interesting is that if I adjust the loop count, I can re-create the issue even with the commit on the inner loops.

This leads me to believe I am unintentionally cross some working memory threshold on the SQLAclhemy ORM side of things.

Does this seem reasonable?

**Comment by ankane** [comment]
Re logs: Postgres should log errors (and the statements that cause them) in the server log by default. The relevant lines will look like:

```text
ERROR:  invalid input syntax for type vector: ...
STATEMENT:  SELECT ...
```

Re memory threshold: I'm not aware of something like that. If you can create a single file script to reproduce, happy to look into it more.

**Comment by ankane** [comment]
Closing due to no response
