### ISSUE TITLE
cannot import name 'register_vector' from 'psycopg' 

### ISSUE THREAD

**Issue by dynamicdeploy** [pgvector/pgvector-python#91]
I am getting this for psycopg3. 
cannot import name 'register_vector' from 'psycopg' 
Mac OS
psycopg 3.2.2
vector extensions is enabled and works from pgAdmin in Postgres

This is the code. I haven't gotten anything to work so far. Tried all options and read all articles. 

import psycopg
import numpy as np
from psycopg import register_vector

with psycopg.connect("postgresql://xxx:xxx$@localhost:5432/xxx") as conn:
     
        conn.execute('CREATE EXTENSION IF NOT EXISTS vector')
        
        register_vector(conn)
        conn.execute('CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3))')
        # https://github.com/pgvector/pgvector-python/issues/4 <-- tried everything from here.
        
        embedding = np.array([1, 2, 3])
        conn.execute('INSERT INTO items (embedding) VALUES (%s)', (embedding,))
        conn.execute('SELECT * FROM items ORDER BY embedding <-> %s LIMIT 5', (embedding,)).fetchall()

**Comment by ankane** [comment]
Hi @dynamicdeploy, the correct import is:

```python
from pgvector.psycopg import register_vector
````

[Docs](https://github.com/pgvector/pgvector-python?tab=readme-ov-file#psycopg-3)

**Comment by dynamicdeploy** [comment]
Then the compiler complains "Import "pgvector.psycopg" could not be resolved"

**Comment by ankane** [comment]
It looks like that's a Pylance error (not specific to pgvector). Please use other resources for help.
