### ISSUE TITLE
Loss of Precision in Embeddings Due to np.float32 in pgvector

### ISSUE THREAD

**Issue by miskibin** [pgvector/pgvector-python#97]
In the `pgvector\django\vector.py` module, vectors are stored as `np.float32`:

```python
def to_python(self, value):
    if isinstance(value, list):
        return np.array(value, dtype=np.float32)
    return Vector._from_db(value)
```

In some cases, critical information about the embeddings is lost.

In the image, red represents the original embedding and green represents the embedding after being parsed by this function:

![image](https://github.com/user-attachments/assets/c8e2e847-9397-4199-bfe1-0a0b0ddb4bcc)

Could this be made parametrizable or customizable in some way?

**Comment by ankane** [comment]
Hi @miskibin, the `vector` type uses [single-precision floats](https://github.com/pgvector/pgvector/?tab=readme-ov-file#vector-type). You can use [different data types](https://github.com/pgvector/pgvector/?tab=readme-ov-file#can-i-store-vectors-with-more-precision) to store values with more precision.
